api_platform:
    title: Hello API Platform
    version: 1.0.0
    patch_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/x-www-form-urlencoded' ]
        jsonapi: [ 'application/vnd.api+json' ]
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResources'
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
