name: CI

on:
  push:
    branches:
      - main
      - feature/mep 
  pull_request: ~
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: | 
            cd /var/www/html/
            git clone git@github.com:kidelag/challenge-api-platform-vue.git
            cd challenge-api-platform-vue
            npm install
            composer install
